# Site settings
title: Iva Goldsmith
email: Aurif3x@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  “Web developer in Philadelphia, PA.” 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ivagold.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
gems:
  - jemoji